(()=>{
'use strict';
const app=document.getElementById('app'),key='pm-khairun-prototype-v1';
const defaults=()=>({answers:['','',[], ''],selected:'',variant:'',compare:[],purpose:'Bantu pilih varian',share:true,trade:'',tradeShare:true,old:{brand:'',model:'',year:'',mileage:'',loan:''}});
let state=defaults(),storage=true,internalDepth=0;
const answerChoices=[['Ulang-alik','Keluarga','Perjalanan jauh','Pelbagai kegunaan'],['5','7'],['Kos penggunaan','Keselesaan','Ruang','Teknologi','Prestasi'],['Sedan','SUV','Belum pasti']];
const purposes=['Bantu pilih varian','Semak promosi','Minta sebut harga','Tanya slot test drive'];
function restore(saved){
 if(!saved||typeof saved!=='object')return;
 if(Array.isArray(saved.answers))state.answers=answerChoices.map((choices,i)=>i===2?(Array.isArray(saved.answers[i])?[...new Set(saved.answers[i].filter(x=>choices.includes(x)))].slice(0,2):[]):choices.includes(saved.answers[i])?saved.answers[i]:'');
 if(PM.get(saved.selected))state.selected=saved.selected;
 if(typeof saved.variant==='string')state.variant=saved.variant;
 state.compare=Array.isArray(saved.compare)?[...new Set(saved.compare.filter(id=>PM.get(id)))].slice(0,2):[];
 if(purposes.includes(saved.purpose))state.purpose=saved.purpose;
 if(['','yes','maybe','no'].includes(saved.trade))state.trade=saved.trade;
 for(const k of ['share','tradeShare'])if(typeof saved[k]==='boolean')state[k]=saved[k];
 for(const k of Object.keys(state.old))if(typeof saved.old?.[k]==='string')state.old[k]=saved.old[k].slice(0,k==='year'?4:60);
 for(const k of ['year','mileage'])state.old[k]=state.old[k].replace(/\D/g,'');
 if(!['','Ya','Tidak','Tidak pasti'].includes(state.old.loan))state.old.loan='';
}
try{restore(JSON.parse(sessionStorage.getItem(key)))}catch{try{sessionStorage.removeItem(key)}catch{storage=false}}
if(!PM.get(state.selected)){state.selected='';state.variant=''}
state.compare=Array.isArray(state.compare)?state.compare.filter(id=>PM.get(id)).slice(0,2):[];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{sessionStorage.setItem(key,JSON.stringify(state))}catch{storage=false}};
const link=(label,route,primary=false)=>`<a class="button ${primary?'primary':''}" href="#${route}">${label}</a>`;
const back=()=>'<button class="back" data-act="back">← Kembali</button>';
const powerLabel=p=>({Petrol:'Petrol',EV:'Elektrik penuh',PHEV:'Hibrid plug-in'}[p]||p);
const sourceLinks=m=>`<small>Semakan: ${PM.reviewed} · <a href="${m.source}" target="_blank" rel="noopener noreferrer">Laman rasmi</a> · <a href="${m.variantSource}" target="_blank" rel="noopener noreferrer">Rujukan varian</a></small>`;
const modelImage=m=>`<img class="model-image" src="assets/${m.id}.png" alt="${m.name}" width="720" height="400" loading="lazy">`;
const catalogCard=m=>`<article class="panel model-card">${modelImage(m)}<span class="pill">${m.type} · ${powerLabel(m.power)}</span><h2>${m.name}</h2><p>${m.note}</p><small>${m.seatsLabel||m.seats+' tempat duduk'}</small><div class="actions">${link('Kenali model','model/'+m.id,true)}<button data-compare="${m.id}" aria-pressed="${state.compare.includes(m.id)}">${state.compare.includes(m.id)?'Buang banding':'Tambah banding'}</button></div><p>${sourceLinks(m)}</p></article>`;
function msg(){
 const lines=['Salam Khairun. Saya datang daripada ProtonMatch.'];
 if(state.share){const m=PM.get(state.selected);if(m){lines.push('Model diminati: '+m.name+'.');if(state.variant&&PM.variants(m,state.answers[1]).includes(state.variant))lines.push('Varian: '+state.variant+'.');}if(state.answers[0])lines.push('Penggunaan: '+state.answers[0]+'.');if(state.answers[2].length)lines.push('Keutamaan: '+state.answers[2].join(', ')+'.')}
 lines.push('Tujuan: '+state.purpose+'.');
 if(['yes','maybe'].includes(state.trade)){lines.push(state.trade==='yes'?'Saya berminat untuk trade-in kereta lama.':'Saya masih mempertimbangkan trade-in.');if(state.tradeShare)for(const [k,t]of Object.entries({brand:'Jenama lama',model:'Model lama',year:'Tahun',mileage:'Anggaran perbatuan (km)',loan:'Masih ada pinjaman'})){if(state.old[k])lines.push(t+': '+state.old[k]+'.')}lines.push('Boleh bantu semak proses trade-in?')}
 return lines.join('\n');
}
const qs=[['Kereta ini paling banyak untuk apa?',['Ulang-alik','Keluarga','Perjalanan jauh','Pelbagai kegunaan']],['Minimum tempat duduk yang diperlukan?',['5','7']],['Apa paling penting untuk anda?',['Kos penggunaan','Keselesaan','Ruang','Teknologi','Prestasi']],['Ada bentuk kereta pilihan?',['Sedan','SUV','Belum pasti']]];
function render(){
 const route=location.hash.slice(1)||'home';let html='';
 if(route==='home')html=`<section class="hero"><div class="hero-copy"><span class="eyebrow">KHAIRUN PROTON · SEREMBAN</span><h1>Proton anda.<br><em>Cara anda.</em></h1><p>Saya bantu anda cari Proton yang sesuai untuk perjalanan harian, keluarga dan langkah seterusnya.</p><div class="actions">${link('Cari Proton saya','question/0',true)}${link('Saya dah ada model','catalog')}</div><small>4 soalan ringkas · Tiada pendaftaran</small></div><div class="hero-visual"><span class="hero-model" aria-hidden="true">X50</span><img src="assets/x50.png" alt="Proton X50" width="720" height="400" fetchpriority="high"><a href="#model/x50" class="hero-caption">Kenali Proton X50 ↗</a></div></section><nav class="model-nav" aria-label="Pilihan model">${PM.catalog.filter(m=>PM.get(m.id)).map(m=>`<a href="#model/${m.id}">${m.name}</a>`).join('')}</nav><section class="home-section"><div class="section-heading"><div><span class="eyebrow">TEROKA PILIHAN</span><h2>Ke mana perjalanan anda?</h2></div>${link('Lihat semua model','catalog')}</div><div class="model-showcase">${PM.catalog.filter(m=>PM.get(m.id)).map(m=>`<a class="showcase-item" href="#model/${m.id}">${modelImage(m)}<small>${m.type}</small><h3>${m.name} <span>↗</span></h3></a>`).join('')}</div></section><section class="advisor-feature"><img src="assets/khairun.jpg" alt="Khairun, Perunding Jualan Proton" width="836" height="1256" loading="lazy"><div><span class="eyebrow">SA PROTON ANDA</span><h2>Hai, saya Khairun.</h2><p>Saya bantu anda semak pilihan model, varian, promosi, rebat, baucar dan urusan trade-in. Tanya saya tentang tawaran yang tersedia untuk model pilihan anda.</p><p class="muted">HZN Resources Sdn. Bhd.<br>Seremban, Negeri Sembilan</p>${link('Bincang dengan Khairun','summary',true)}</div></section><div class="actions"> <button data-act="reset">Mula semula pilihan saya</button></div>`;
 else if(route.startsWith('question/')){const i=Number(route.split('/')[1]);if(!Number.isInteger(i)||!qs[i])return invalid();html=`${back()}<div class="form"><span class="eyebrow">SOALAN ${i+1} DARIPADA 4</span><div class="progress" aria-label="Soalan ${i+1} daripada 4">${qs.map((_,n)=>`<span class="${n<=i?'done':''}"></span>`).join('')}</div><h1>${qs[i][0]}</h1>${i===2?'<p class="muted">Pilih satu atau dua. Anda boleh ubah kemudian.</p>':''}<fieldset><legend class="muted">Pilihan anda</legend>${qs[i][1].map(o=>`<label class="option"><input type="${i===2?'checkbox':'radio'}" name="answer" data-q="${i}" value="${o}" ${(i===2?state.answers[i].includes(o):state.answers[i]===o)?'checked':''}>${o}${i===1?' tempat duduk':''}</label>`).join('')}</fieldset><div class="actions"><button class="primary" data-next="${i}" ${state.answers[i].length?'':'disabled'}>${i===3?'Lihat padanan':'Seterusnya'}</button></div></div>`}
 else if(route==='results'){const matches=PM.match(state.answers);html=`${back()}<span class="eyebrow">SENARAI PENDEK ANDA</span><h1>Pilihan untuk diteroka.</h1><p class="muted">Padanan awal berdasarkan keperluan anda. Saya boleh bantu anda semak pilihan ini dengan lebih lanjut. Ciri sebenar bergantung pada varian.</p>${state.answers[2].includes('Kos penggunaan')?'<p class="notice">Kos penggunaan belum dikira dalam padanan ini. Khairun boleh membantu menyemak anggaran yang berkaitan.</p>':''}<div class="grid">${matches.map(({model:m},i)=>`<div><p class="eyebrow">${i===2?'ALTERNATIF':'CADANGAN '+(i+1)}</p>${catalogCard(m)}<p class="muted">Terdapat varian yang memenuhi minimum ${state.answers[1]} tempat duduk.${m.tags.filter(t=>[state.answers[0],...state.answers[2]].includes(t)).length?' Keutamaan untuk dibincangkan: '+m.tags.filter(t=>[state.answers[0],...state.answers[2]].includes(t)).join(', ')+'.':' Semak kesesuaian keutamaan lain dengan Khairun.'}</p><p>${m.consideration}</p></div>`).join('')||'<p>Tiada padanan yang boleh dipaparkan. Lengkapkan atau ubah keperluan anda, atau berbincang dengan Khairun.</p>'}</div><div class="actions">${link('Ubah jawapan','question/0')}${link('Banding pilihan ('+state.compare.length+'/2)','compare')}</div>`}
 else if(route==='catalog')html=`${back()}<span class="eyebrow">KATALOG KHAS KHAIRUN</span><h1>Lima model. Pilihan anda.</h1><p class="muted">Saga, S70, X50, X70 dan X90. Maklumat produk dirujuk daripada laman rasmi Proton; stok dan promosi disemak terus dengan Khairun.</p><div class="grid">${PM.catalog.filter(m=>PM.get(m.id)).map(catalogCard).join('')}</div><div class="actions">${link('Banding pilihan ('+state.compare.length+'/2)','compare')}</div>`;
 else if(route.startsWith('model/')){const m=PM.get(route.split('/')[1]);if(!m)return invalid();if(state.selected!==m.id){state.selected=m.id;state.variant='';save()}const variants=PM.variants(m,state.answers[1]);if(!variants.includes(state.variant)){state.variant='';save()}html=`${back()}<span class="eyebrow">PROTON BERSAMA KHAIRUN</span><h1>${m.name}</h1><div class="grid"><div class="panel"><span class="pill">${m.type} · ${m.seatsLabel||m.seats+' tempat duduk'}</span><h2>Kenali pilihan ini</h2><p>${m.note}</p><h3>Perkara untuk dipertimbangkan</h3><p>${m.consideration}</p>${sourceLinks(m)}${m.announcement?`<p><a href="${m.announcement}" target="_blank" rel="noopener noreferrer">Maklumat rasmi S70 Lite dan Prime</a></p>`:''}</div><div class="panel"><h2>Teroka varian</h2><label class="field">Pilihan varian<select id="variant"><option value="">Belum pasti — bantu saya pilih</option>${variants.map(v=>`<option ${v===state.variant?'selected':''}>${v}</option>`).join('')}</select></label>${m.id==='x90'&&state.answers[1]==='7'?'<p class="notice">Prime X tidak disenaraikan kerana anda memerlukan tujuh tempat duduk.</p>':''}<p class="muted">Anda boleh bertanya tanpa memilih varian. Semak harga, stok dan kelengkapan varian dengan Khairun.</p><div class="actions">${link('Tanya tentang model ini','summary',true)}<button data-compare="${m.id}">${state.compare.includes(m.id)?'Buang banding':'Tambah banding'}</button>${link('Lihat perbandingan','compare')}</div></div></div>`}
 else if(route==='compare'){const models=state.compare.map(id=>PM.get(id));html=`${back()}<h1>Banding dua pilihan.</h1>${models.length===2?`<div class="panel"><table class="table"><caption>Perbandingan model · Ciri bergantung pada varian</caption><thead><tr><th>Perkara</th>${models.map(m=>`<th>${m.name}</th>`).join('')}</tr></thead><tbody>${[['Bentuk','type'],['Tempat duduk','seats']].map(([t,k])=>`<tr><th>${t}</th>${models.map(m=>`<td>${k==='seats'?(m.seatsLabel||m.seats):m[k]}</td>`).join('')}</tr>`).join('')}<tr><th>Fokus penerokaan</th>${models.map(m=>`<td>${m.tags.join(', ')}</td>`).join('')}</tr><tr><th>Teruskan</th>${models.map(m=>`<td>${link('Kenali model','model/'+m.id)}</td>`).join('')}</tr></tbody></table></div>`:'<p>Pilih dua model daripada katalog untuk dibandingkan.</p>'}<div class="actions">${link('Ubah pilihan dalam katalog','catalog')}</div>`}
 else if(route==='summary'){html=`${back()}<h1>Semak pertanyaan anda.</h1><div class="grid"><div><label class="field">Tujuan pertanyaan<select id="purpose">${['Bantu pilih varian','Semak promosi','Minta sebut harga','Tanya slot test drive'].map(x=>`<option ${state.purpose===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="option"><input id="share" type="checkbox" ${state.share?'checked':''}>Sertakan pilihan model dan keutamaan</label><label class="field">Ada kereta untuk trade-in?<select id="trade">${[['','Pilih jika berkaitan'],['yes','Ya, saya berminat'],['maybe','Masih mempertimbangkan'],['no','Tiada']].map(([v,t])=>`<option value="${v}" ${state.trade===v?'selected':''}>${t}</option>`).join('')}</select></label><div id="trade-fields" ${['yes','maybe'].includes(state.trade)?'':'hidden'}><h2>Kereta lama anda</h2><p class="muted">Mana-mana jenama. Semua butiran pilihan; ini bukan penilaian harga atau jaminan penerimaan.</p>${[['brand','Jenama','Contoh: Perodua'],['model','Model','Contoh: Myvi'],['year','Tahun','Contoh: 2018'],['mileage','Anggaran perbatuan (km)','Contoh: 90000']].map(([k,t,p])=>`<label class="field">${t}<input data-old="${k}" value="${esc(state.old[k])}" placeholder="${p}" maxlength="${k==='year'?4:60}" ${['year','mileage'].includes(k)?'inputmode="numeric"':''}></label>`).join('')}<label class="field">Masih ada pinjaman?<select data-old="loan">${['','Ya','Tidak','Tidak pasti'].map(x=>`<option value="${x}" ${state.old.loan===x?'selected':''}>${x||'Tidak dinyatakan'}</option>`).join('')}</select></label><label class="option"><input id="tradeShare" type="checkbox" ${state.tradeShare?'checked':''}>Sertakan butiran kereta lama</label></div></div><div class="panel"><h2>Mesej untuk Khairun</h2><p id="message" class="summary"></p><div class="actions"><a class="button primary" id="whatsapp-link" target="_blank" rel="noopener noreferrer">Teruskan ke WhatsApp</a><button data-act="copy">Salin mesej</button></div><p class="muted" id="status" role="status">Penerima: Khairun · 017-203 2996. Anda perlu menekan Hantar sendiri dalam WhatsApp.</p></div></div>`}
 else return invalid();
 document.body.dataset.page=route.split('/')[0];app.classList.toggle('home',route==='home');app.innerHTML=html+(!storage?'<p class="notice">Simpanan sesi tidak tersedia. Pilihan mungkin hilang selepas refresh.</p>':'');if(route.startsWith('model/')){const m=PM.get(route.split('/')[1]);if(m)app.querySelector('h1').insertAdjacentHTML('afterend',modelImage(m))}if(route==='summary')updateMessage();
}
function invalid(){app.classList.remove('home');document.body.dataset.page='invalid';app.innerHTML='<h1>Pilihan tidak tersedia.</h1><p>Hanya ID daripada katalog Proton Khairun dibenarkan. Tiada model atau harga bebas diterima.</p>'+link('Kembali ke katalog','catalog',true)}
function updateMessage(){const node=document.getElementById('message');if(node)node.textContent=msg();const wa=document.getElementById('whatsapp-link');if(wa)wa.href='https://wa.me/'+PM.advisor.whatsapp+'?text='+encodeURIComponent(msg())}
app.addEventListener('input',e=>{if(e.target.dataset.old){let value=e.target.value;if(['year','mileage'].includes(e.target.dataset.old)){value=value.replace(/\D/g,'');e.target.value=value}state.old[e.target.dataset.old]=value;save();updateMessage()}});
app.addEventListener('change',e=>{const t=e.target;if(t.dataset.q){const i=Number(t.dataset.q);if(i===2){let values=Array.from(app.querySelectorAll('[data-q="2"]:checked')).map(x=>x.value);if(values.length>2){t.checked=false;return}state.answers[i]=values}else state.answers[i]=t.value;app.querySelector('[data-next]').disabled=!state.answers[i].length}
 if(t.id==='variant'){const m=PM.get(state.selected);state.variant=m&&PM.variants(m,state.answers[1]).includes(t.value)?t.value:''}
 if(t.id==='purpose'&&!purposes.includes(t.value))return;
 if(t.id==='trade'&&!['','yes','maybe','no'].includes(t.value))return;
 if(['purpose','trade','share','tradeShare'].includes(t.id)){state[t.id]=t.type==='checkbox'?t.checked:t.value;if(t.id==='trade')document.getElementById('trade-fields').hidden=!['yes','maybe'].includes(t.value)}
 if(t.dataset.old)state.old[t.dataset.old]=t.value;save();updateMessage();});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.route)location.hash=b.dataset.route;
 if(b.dataset.next!==undefined){const i=Number(b.dataset.next);if(state.answers[i].length)location.hash=i===3?'results':'question/'+(i+1)}
 if(b.dataset.compare){const id=b.dataset.compare;if(!PM.get(id))return;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<2)state.compare.push(id);else{alert('Maksimum dua pilihan. Buang satu pilihan dahulu.');return}save();render()}
 if(b.dataset.act==='back'){if(internalDepth>0){internalDepth-=2;history.back()}else location.hash='home'}
 if(b.dataset.act==='reset'&&confirm('Padam jawapan dan pilihan sesi ini?')){state=defaults();save();location.hash='home';render()}
 if(b.dataset.act==='copy'){try{await navigator.clipboard.writeText(msg());document.getElementById('status').textContent='Mesej disalin. Tiada mesej dihantar.'}catch{document.getElementById('status').textContent='Salinan automatik tidak tersedia. Pilih dan salin teks mesej secara manual.'}}
});
window.addEventListener('hashchange',()=>{internalDepth=Math.max(0,internalDepth+1);render();app.focus({preventScroll:true});window.scrollTo(0,0)});render();
})();
