/* Internal showroom views. Source of truth: data/*.json. No third-party runtime. */
globalThis.Showroom = (() => {
  'use strict';
  const data = SHOWROOM_DATA.models;
  const money = n => 'RM ' + Number(n).toLocaleString('en-MY', {maximumFractionDigits: 0});
  const priceNote = 'OTR Semenanjung Malaysia · individu persendirian · tanpa insurans · sebelum rebat';
  const today = () => new Intl.DateTimeFormat('en-CA', {timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  function calculate(price, deposit, rate, years) {
    if (![price,deposit,rate,years].every(Number.isFinite) || price<=0 || deposit<0 || deposit>price || rate<0 || rate>20 || ![5,7,9].includes(years)) return null;
    const principal = price-deposit, interest = principal*rate/100*years;
    return {principal,interest,total:principal+interest,monthly:(principal+interest)/(years*12)};
  }
  function testDriveMessage({name,model,variant,date,time}) {
    const m=PM.get(model), v=data[model]?.variants.find(v=>v.name===variant);
    if(!m||!v||!name.trim()||name.trim().length>80||!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<today()||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) return null;
    const dt=new Date(date+'T'+time+':00+08:00');
    if(!Number.isFinite(dt.getTime())||dt<=new Date()||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)return null;
    return `Salam Khairun, saya ingin memohon test drive melalui ProtonMatch.\n\nNama: ${name.trim()}\nModel: ${m.name}\nVarian: ${v.name}\nTarikh pilihan: ${date}\nMasa pilihan: ${time} (waktu Malaysia)\nLokasi: ${PM.advisor.showroom}, Seremban\n\nBoleh bantu sahkan ketersediaan model dan slot ini?`;
  }
  const wa = message => 'https://wa.me/'+PM.advisor.whatsapp+'?text='+encodeURIComponent(message);
  function create({state,save,esc,link,back}) {
    let comparison = [], differenceOnly=false;
    let loan={deposit:null,rate:3,years:9,selection:''};
    let booking={name:'',date:'',time:''};
    const getModel=()=>PM.get(state.selected)||PM.get('saga');
    const getVariant=m=>data[m.id].variants.find(v=>v.name===state.variant)||data[m.id].variants[0];
    const opts=(values,selected)=>values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('');
    const ul=items=>`<ul class="feature-list">${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`;
    const source=m=>`<details class="source-details"><summary>Sumber rasmi & tarikh semakan</summary><p>Disemak 4 Oktober 2026. Harga dan spesifikasi tertakluk kepada perubahan. Rujukan di bawah adalah pilihan; maklumat utama tersedia dalam showroom ini.</p><div class="source-links"><a href="${m.source}" target="_blank" rel="noopener noreferrer">Halaman Proton ↗</a><a href="${data[m.id].brochure}" target="_blank" rel="noopener noreferrer">Brosur spesifikasi ↗</a><a href="${data[m.id].priceSource}" target="_blank" rel="noopener noreferrer">Sumber harga ↗</a>${data[m.id].additionalPriceSource?`<a href="${data[m.id].additionalPriceSource}" target="_blank" rel="noopener noreferrer">Harga Lite & Prime ↗</a>`:''}</div></details>`;
    const picker=(m,v)=>`<div class="grid picker"><label class="field">Model<select id="advisor-model">${PM.catalog.map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${x.name}</option>`).join('')}</select></label><label class="field">Varian<select id="advisor-variant">${opts(data[m.id].variants.map(x=>x.name),v.name)}</select></label></div>`;
    function selected(){const m=getModel(),v=getVariant(m);state.selected=m.id;state.variant=v.name;save();return {m,v};}
    function model(m) {
      const d=data[m.id];
      if(state.selected!==m.id){state.selected=m.id;state.variant='';}
      const allowed=PM.variants(m,state.answers[1]);
      if(!allowed.includes(state.variant))state.variant=allowed[0]||m.variants[0];
      const v=getVariant(m);save();
      return `${back()}<div class="showroom-heading"><span class="eyebrow">DIGITAL SHOWROOM / ${esc(d.edition)}</span><h1>${m.name}<span class="title-dot">.</span></h1><p>Kenali setiap pilihan. Rancang langkah seterusnya.</p></div>
      <section class="model-stage"><div class="stage-image"><span class="watermark" aria-hidden="true">${m.id.toUpperCase()}</span><img src="assets/${m.id}.png" alt="${m.name}, gambar ilustrasi model" width="720" height="400"><span class="stage-caption">${m.type} · ${m.seatsLabel||m.seats+' tempat duduk'}</span></div><div class="stage-content"><span class="eyebrow">VARIAN PILIHAN ANDA</span><label class="field">Pilih varian<select id="variant">${opts(allowed,v.name)}</select></label><div class="model-price">${money(v.price)}</div><small>${priceNote}</small><p id="variant-note" class="variant-note">${esc(m.variantNotes?.[v.name]||v.engine+' · '+v.ps+' PS · '+v.nm+' Nm · '+v.transmission)}</p>${m.id==='x90'&&state.answers[1]==='7'?'<p class="notice">Prime X mempunyai enam tempat duduk; ditapis kerana pilihan anda ialah minimum tujuh.</p>':''}<div class="actions">${link('Kira ansuran','loan',true)}${link('Book test drive','test-drive')}</div><a class="text-link" href="#summary">Tanya Khairun tentang varian ini ↗</a></div></section>
      <nav class="section-nav" aria-label="Bahagian model">${[['specs','Spesifikasi'],['features','Kelengkapan'],['variants','Harga & varian'],['colours','Warna'],['gallery','Galeri']].map(([id,t])=>`<button data-scroll="${id}">${t}</button>`).join('')}</nav>
      <section id="specs" class="detail-section"><span class="eyebrow">01 / SPESIFIKASI</span><h2>Kenali ${esc(v.name)}.</h2><div class="stat-grid">${[[v.ps,'PS / kuasa'],[v.nm,'Nm / tork'],[v.transmission,'Transmisi'],[v.seats,'Tempat duduk']].map(([n,t])=>`<div><strong>${esc(n)}</strong><small>${t}</small></div>`).join('')}</div><dl class="spec-list">${[['Enjin',v.engine+' · 1,499 cc'],['Dimensi (P × L × T)',d.dimensions],['Jarak roda',d.wheelbase],['Tangki bahan api',d.tank],...(d.boot?[['Ruang bagasi',d.boot]]:[])].map(([k,val])=>`<div><dt>${k}</dt><dd>${esc(val)}</dd></div>`).join('')}</dl>${d.note?`<p class="notice">${esc(d.note)}</p>`:''}</section>
      <section id="features" class="detail-section"><span class="eyebrow">02 / KELENGKAPAN VARIAN</span><h2>Keselesaan bertemu keyakinan.</h2><div class="grid"><article class="panel"><h3>Dalam & luar</h3>${ul([...d.highlights,...v.features,`Infotainment: ${v.screen}`,`Tempat duduk: ${v.upholstery}`])}</article><article class="panel"><h3>Keselamatan & bantuan pemanduan</h3><div class="safety-badges"><span>${v.airbags} beg udara</span><span>AEB ${v.aeb?'✓':'—'}</span><span>ACC ${v.acc?'✓':'—'}</span></div>${ul([...v.safety,'Kamera: '+v.camera])}<small>AEB: brek kecemasan autonomi. ACC: kawalan jelajah adaptif. “—” bermaksud tidak disertakan. Bantuan pemanduan tidak menggantikan perhatian pemandu.</small></article></div></section>
      <section id="variants" class="detail-section"><span class="eyebrow">03 / HARGA & VARIAN</span><h2>Pilihan yang sesuai dengan anda.</h2><p class="muted">${priceNote}. Semua varian ditunjukkan untuk rujukan.</p><div class="variant-grid">${d.variants.map(x=>`<article class="panel variant-card ${x.name===v.name?'is-selected':''}"><small>${x.name===v.name?'PILIHAN SEMASA':x.seats+' TEMPAT DUDUK'}</small><h3>${esc(x.name)}</h3><strong class="price">${money(x.price)}</strong><p>${x.ps} PS · ${x.nm} Nm<br>${esc(x.transmission)}</p><button data-pick="${esc(x.name)}" ${!allowed.includes(x.name)?'disabled':''}>${allowed.includes(x.name)?'Pilih varian':'6 tempat duduk'}</button></article>`).join('')}</div><div class="actions"><button data-variant-compare="${m.id}">Banding varian ${m.id.toUpperCase()}</button><button data-compare="${m.id}">${state.compare.includes(m.id)?'Buang banding':'Tambah banding model'}</button>${link('Buka compare','compare')}</div></section>
      <section id="colours" class="detail-section"><span class="eyebrow">04 / WARNA RASMI</span><h2>Warna untuk gaya anda.</h2><div class="colour-list">${d.colours.map((c,i)=>`<button class="colour-option" data-colour="${esc(c)}" aria-pressed="${i===0}"><span class="swatch" style="--swatch:${({'Marine Blue':'#233b65','Space Grey':'#727a87','Jet Grey':'#4a5054','Ruby Red':'#a72331','Armour Silver':'#b5b9bd','Snow White':'#f1f2ef','Quartz Black':'#202124','Teal Bayou Green':'#176777'})[c]}"></span>${esc(c)}</button>`).join('')}</div><p id="colour-status" class="muted" aria-live="polite">${esc(d.colours[0])} · Sampel warna skrin sahaja. Ketersediaan mengikut varian dan stok.</p></section>
      <section id="gallery" class="detail-section"><span class="eyebrow">05 / GALERI</span><h2>Lihat lebih dekat.</h2><div class="gallery-grid">${['exterior','interior'].map((kind,i)=>`<figure><img src="assets/gallery/${m.id}-${kind}.webp" alt="${m.name} ${i?'ruang dalaman':'reka bentuk luaran'} daripada brosur rasmi" loading="lazy" width="1000" height="650"><figcaption>${i?'Ruang dalaman':'Reka bentuk luaran'} · ilustrasi brosur, kelengkapan mengikut varian</figcaption></figure>`).join('')}</div></section>
      <section class="advisor-strip"><div><span class="eyebrow">LANGKAH SETERUSNYA</span><h2>Rasai sendiri ${m.id.toUpperCase()}.</h2><p>Khairun bantu semak model, varian dan slot pilihan anda.</p></div>${link('Book test drive','test-drive',true)}${link('Semak promosi','promotions')}</section>${source(m)}`;
    }
    function compare() {
      if(comparison.length!==2){const ids=state.compare.length===2?state.compare:[getModel().id,getModel().id];comparison=ids.map((id,i)=>({id,name:data[id].variants[i===1&&ids[0]===ids[1]?1:0].name}));}
      const entries=comparison.map(c=>({m:PM.get(c.id),v:data[c.id].variants.find(v=>v.name===c.name)||data[c.id].variants[0]}));
      const rows=[['Harga OTR',...entries.map(x=>money(x.v.price))],['Enjin',...entries.map(x=>x.v.engine)],['Kuasa / tork',...entries.map(x=>x.v.ps+' PS / '+x.v.nm+' Nm')],['Transmisi',...entries.map(x=>x.v.transmission)],['Tempat duduk',...entries.map(x=>x.v.seats)],['Beg udara',...entries.map(x=>x.v.airbags)],['AEB',...entries.map(x=>x.v.aeb?'✓ Ya':'— Tiada')],['ACC',...entries.map(x=>x.v.acc?'✓ Ya':'— Tiada')],['Kamera',...entries.map(x=>x.v.camera)],['Infotainment',...entries.map(x=>x.v.screen)],['Upholsteri',...entries.map(x=>x.v.upholstery)],['Kelengkapan',...entries.map(x=>x.v.features.join(' · '))],['Keselamatan',...entries.map(x=>x.v.safety.join(' · '))],['Dimensi',...entries.map(x=>data[x.m.id].dimensions)]];
      const diff=entries[1].v.price-entries[0].v.price;
      return `${back()}<span class="eyebrow">COMPARE / MODEL & VARIAN</span><h1>Dua pilihan.<br>Lebih jelas.</h1><p>Banding varian dalam model yang sama atau dua model berlainan.</p><div class="grid compare-pickers">${entries.map(({m,v},i)=>`<article class="panel"><span class="eyebrow">PILIHAN ${i+1}</span><img class="model-image" src="assets/${m.id}.png" alt="${m.name}" width="720" height="400"><label class="field">Model ${i+1}<select data-cmp-model="${i}">${PM.catalog.map(x=>`<option value="${x.id}" ${m.id===x.id?'selected':''}>${x.name}</option>`).join('')}</select></label><label class="field">Varian ${i+1}<select data-cmp-variant="${i}">${opts(data[m.id].variants.map(x=>x.name),v.name)}</select></label>${link('Kenali model','model/'+m.id)}</article>`).join('')}</div><div class="compare-summary"><strong>${diff===0?'Harga kedua-dua pilihan sama':`Pilihan 2 ${diff>0?'lebih tinggi':'lebih rendah'} ${money(Math.abs(diff))}`}</strong><p>${diff===0?'Lihat perbezaan kelengkapan di bawah.':`Perbezaan anggaran ${money(calculate(Math.abs(diff),Math.abs(diff)*.1,3,9).monthly)}/bulan pada deposit 10%, kadar rata 3% setahun, 9 tahun.`}</p><small>${priceNote}. Anggaran sahaja; bukan tawaran bank.</small></div><label class="option"><input id="differences-only" type="checkbox" ${differenceOnly?'checked':''}>Tunjukkan perbezaan sahaja</label><div class="table-scroll" role="region" aria-label="Jadual perbandingan" tabindex="0"><table class="table comparison-table"><caption>Spesifikasi varian pilihan</caption><thead><tr><th scope="col">Perkara</th>${entries.map(x=>`<th scope="col">${x.m.name}<br>${esc(x.v.name)}</th>`).join('')}</tr></thead><tbody>${rows.filter(r=>!differenceOnly||r[1]!==r[2]).map(([label,a,b])=>`<tr class="${a!==b?'different':''}"><th scope="row">${label}</th><td>${esc(a)}</td><td>${esc(b)}</td></tr>`).join('')||'<tr><td colspan="3">Tiada perbezaan untuk pilihan yang sama.</td></tr>'}</tbody></table></div>${entries.map(x=>source(x.m)).join('')}`;
    }
    function loanPage(){
      const {m,v}=selected();const selection=m.id+v.name;
      if(loan.selection!==selection){loan.deposit=Math.round(v.price*.1);loan.selection=selection;}
      return `${back()}<span class="eyebrow">RANCANG PEMILIKAN</span><h1>Ansuran dalam jangkauan.</h1><p>Harga diambil terus daripada varian pilihan anda.</p>${picker(m,v)}<div class="grid"><form id="loan-form" class="panel"><h2>Ubah anggaran anda</h2><p><strong>${money(v.price)}</strong><br><small>${priceNote}</small></p><label class="field">Deposit (RM)<input id="loan-deposit" type="number" min="0" max="${v.price}" step="1" required value="${loan.deposit}"></label><label class="field">Kadar faedah rata (% setahun)<input id="loan-rate" type="number" min="0" max="20" step="0.01" required value="${loan.rate}"></label><label class="field">Tempoh pembiayaan<select id="loan-years">${[5,7,9].map(n=>`<option value="${n}" ${loan.years===n?'selected':''}>${n} tahun</option>`).join('')}</select></label><small>Kadar 3% ialah contoh pengiraan dan boleh diubah. Gunakan kadar rata yang dinyatakan bank; kadar efektif bukan kadar rata.</small></form><section class="loan-result" aria-label="Anggaran pembiayaan"><span class="eyebrow">ANGGARAN BULANAN</span><div id="loan-result" aria-live="polite"></div><p>Anggaran kaedah kadar rata sahaja. Insurans, fi tambahan dan rebat tidak termasuk. Tawaran sebenar bergantung pada bank dan kelayakan anda.</p><div class="actions">${link('Minta sebut harga','summary',true)}${link('Book test drive','test-drive')}</div></section></div><details class="source-details"><summary>Cara anggaran dikira</summary><p>Pokok = harga − deposit. Faedah = pokok × kadar rata setahun × tempoh tahun. Ansuran = (pokok + faedah) ÷ bilangan bulan. Ini simulasi, bukan jadual bayaran atau kelulusan pembiayaan.</p></details>${source(m)}`;
    }
    function updateLoan(){const box=document.getElementById('loan-result');if(!box)return;const result=calculate(getVariant(getModel()).price,loan.deposit,loan.rate,loan.years);box.innerHTML=result?`<strong class="monthly">${money(result.monthly)}<small>/ bulan</small></strong><dl class="loan-breakdown"><div><dt>Jumlah pinjaman</dt><dd>${money(result.principal)}</dd></div><div><dt>Jumlah faedah</dt><dd>${money(result.interest)}</dd></div><div><dt>Jumlah bayaran pinjaman</dt><dd>${money(result.total)}</dd></div></dl>`:'<p class="notice">Masukkan deposit antara RM0 dan harga kereta, serta kadar 0–20%.</p>';}
    function testDrive(){const {m,v}=selected();return `${back()}<span class="eyebrow">BERSAMA KHAIRUN / SEREMBAN</span><h1>Cuba. Rasa. Pilih.</h1><p>Mohon slot test drive untuk model pilihan anda.</p><form id="test-drive-form"><div class="grid"><div class="panel"><label class="field">Nama anda<input id="booking-name" name="name" autocomplete="name" maxlength="80" required value="${esc(booking.name)}"></label>${picker(m,v)}<div class="grid"><label class="field">Tarikh pilihan<input id="booking-date" name="date" type="date" min="${today()}" required value="${esc(booking.date)}"></label><label class="field">Masa pilihan (Malaysia)<input id="booking-time" name="time" type="time" required value="${esc(booking.time)}"></label></div><p class="muted">${PM.advisor.showroom}<br>${PM.advisor.address}</p></div><div class="panel"><h2>Permohonan anda</h2><p>${m.name} · ${esc(v.name)}</p><p id="booking-preview" class="summary" aria-live="polite">Lengkapkan nama, tarikh dan masa untuk menyediakan mesej.</p><button type="submit" class="primary">Buka WhatsApp Khairun ↗</button><p id="booking-status" role="status" class="muted">Penerima: ${PM.advisor.displayPhone}. Slot hanya disahkan selepas Khairun membalas. Anda perlu menekan Hantar dalam WhatsApp.</p><small>Maklumat borang digunakan untuk mesej WhatsApp sahaja. Nama dan jadual tidak disimpan selepas halaman dimuat semula.</small></div></div></form>`;}
    function updateBooking(){const box=document.getElementById('booking-preview');if(!box)return;box.textContent=testDriveMessage({...booking,model:state.selected,variant:state.variant})||'Lengkapkan nama dan pilih tarikh serta masa yang akan datang.';}
    function promotions(){const p=SHOWROOM_DATA.promotions,active=p.offers.filter(x=>x.starts<=today()&&x.ends>=today());return `${back()}<span class="eyebrow">PROMOSI / BERASINGAN DARIPADA HARGA RASMI</span><h1>Semak tawaran anda.</h1><p>Harga katalog kekal sebelum rebat. Promosi mempunyai syarat dan tempoh tersendiri.</p><div class="grid">${active.map(o=>`<article class="panel"><span class="pill">Kempen ${esc(o.owner)}</span><h2>${esc(o.title)}</h2><p>${esc(o.description)}</p><p><strong>Tempoh: ${o.starts} hingga ${o.ends}</strong></p><div class="actions">${link('Teroka '+o.model.toUpperCase(),'model/'+o.model,true)}<a class="button" href="${wa('Salam Khairun, boleh semak kelayakan saya untuk '+o.title+'?')}" target="_blank" rel="noopener noreferrer">Semak kelayakan ↗</a></div><details class="source-details"><summary>Sumber kempen</summary><a href="${o.source}" target="_blank" rel="noopener noreferrer">Pengumuman rasmi Proton ↗</a></details></article>`).join('')||'<p class="notice">Tiada kempen bertarikh yang aktif dalam rekod aplikasi. Tanya Khairun tentang tawaran terbaru.</p>'}<article class="panel"><span class="eyebrow">TAWARAN KHAIRUN</span><h2>Bincang keperluan anda.</h2><p>${esc(p.advisorNote)}</p>${link('Tanya Khairun','summary',true)}</article></div><p class="muted">Rekod promosi disemak 4 Oktober 2026. Semak sambungan internet dan pengesahan Khairun sebelum membuat keputusan.</p>`;}
    return {
      model,compare,loanPage,testDrive,promotions,
      afterRender(){
        updateLoan();updateBooking();
        const float=document.getElementById('floating-whatsapp');
        if(float){const m=PM.get(state.selected);float.href=wa('Salam Khairun, saya datang daripada ProtonMatch.'+(m?' Saya berminat dengan '+m.name+(state.variant?' '+state.variant:'')+'.':''));}
        for(const a of document.querySelectorAll('.app-nav a'))a.setAttribute('aria-current',location.hash===a.getAttribute('href')?'page':'false');
      },
      change(t){
        if(t.id==='advisor-model'&&data[t.value]){state.selected=t.value;state.variant=data[t.value].variants[0].name;return true;}
        if(t.id==='advisor-variant'&&data[getModel().id].variants.some(v=>v.name===t.value)){state.variant=t.value;return true;}
        if(t.dataset.cmpModel!==undefined){const i=Number(t.dataset.cmpModel);if(![0,1].includes(i)||!data[t.value])return false;comparison[i]={id:t.value,name:data[t.value].variants[0].name};return true;}
        if(t.dataset.cmpVariant!==undefined){const i=Number(t.dataset.cmpVariant);if(![0,1].includes(i)||!data[comparison[i].id].variants.some(v=>v.name===t.value))return false;comparison[i].name=t.value;return true;}
        if(t.id==='differences-only'){differenceOnly=t.checked;return true;}
        if(t.id==='loan-years'){loan.years=Number(t.value);updateLoan();}
        return false;
      },
      input(t){
        if(t.id==='loan-deposit'||t.id==='loan-rate'){loan[t.id==='loan-deposit'?'deposit':'rate']=t.value===''?NaN:Number(t.value);updateLoan();}
        const k={'booking-name':'name','booking-date':'date','booking-time':'time'}[t.id];if(k){booking[k]=t.value;updateBooking();}
      },
      click(b){
        if(b.dataset.scroll){document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'auto',block:'start'});return false;}
        if(b.dataset.pick&&PM.variants(getModel(),state.answers[1]).includes(b.dataset.pick)){state.variant=b.dataset.pick;return true;}
        if(b.dataset.variantCompare&&data[b.dataset.variantCompare]){const d=data[b.dataset.variantCompare];comparison=d.variants.slice(0,2).map(v=>({id:d.id,name:v.name}));location.hash='compare';return false;}
        if(b.dataset.compare)comparison=[];
        if(b.dataset.colour){for(const c of document.querySelectorAll('[data-colour]'))c.setAttribute('aria-pressed',String(c===b));document.getElementById('colour-status').textContent=b.dataset.colour+' · Sampel warna skrin sahaja. Semak ketersediaan dengan Khairun.';}
        return false;
      },
      submit(e){
        if(e.target.id==='loan-form'){e.preventDefault();return;}
        if(e.target.id!=='test-drive-form')return;
        e.preventDefault();
        const message=testDriveMessage({...booking,model:state.selected,variant:state.variant});
        if(!message){document.getElementById('booking-status').textContent='Sila lengkapkan nama dan pilih tarikh serta masa yang akan datang.';return;}
        window.open(wa(message),'_blank','noopener,noreferrer');
        document.getElementById('booking-status').innerHTML=`Mesej telah disediakan. Jika WhatsApp tidak terbuka, <a href="${wa(message)}" target="_blank" rel="noopener noreferrer">tekan di sini</a>. Permohonan belum disahkan.`;
      }
    };
  }
  return {create,calculate,testDriveMessage,today,money};
})();
