const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});
 const page=await context.newPage(), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.TEST_URL||'http://127.0.0.1:8000/';
 const go=async route=>{await page.goto(base+'#'+route);await page.waitForFunction(()=>document.getElementById('app').innerHTML.length>100);};
 fs.mkdirSync('test-output',{recursive:true});
 await go('home');
 await page.locator('.skip-link').focus();await page.locator('.skip-link').press('Enter');assert.ok(page.url().endsWith('#home'));
 await page.getByRole('link',{name:'Cari Proton saya',exact:true}).click();
 await page.getByLabel('Keluarga',{exact:true}).check();await page.getByRole('button',{name:'Seterusnya'}).click();
 await page.getByLabel('7 tempat duduk',{exact:true}).check();await page.getByRole('button',{name:'Seterusnya'}).click();
 await page.getByLabel('Ruang',{exact:true}).check();await page.getByRole('button',{name:'Seterusnya'}).click();
 await page.getByLabel('SUV',{exact:true}).check();await page.getByRole('button',{name:'Lihat padanan'}).click();
 await page.waitForURL('**/#results');assert.equal(await page.locator('.model-card').count(),1);
 await page.getByRole('link',{name:'Kenali model',exact:true}).click();
 await page.waitForURL('**/#model/x90');assert.equal(await page.locator('#variant option').count(),2);
 assert.ok(!(await page.locator('#variant').textContent()).includes('Prime X'));
 await page.locator('.app-nav a[href="#home"]').click();
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Mula semula pilihan saya'}).click();
 await go('model/s70');
 await page.selectOption('#variant','1.5 Prime');assert.match(await page.locator('.model-price').textContent(),/62,800/);
 await page.getByRole('link',{name:'Kira ansuran',exact:true}).last().click();await page.waitForURL('**/#loan');
 assert.equal(await page.inputValue('#advisor-variant'),'1.5 Prime');
 assert.equal(await page.inputValue('#loan-deposit'),'6280');
 await page.fill('#loan-deposit','10000');await page.fill('#loan-rate','3');await page.selectOption('#loan-years','7');
 assert.match(await page.locator('#loan-result').textContent(),/761/);
 await page.fill('#loan-deposit','999999');assert.match(await page.locator('#loan-result').textContent(),/Masukkan deposit/);
 await page.selectOption('#advisor-model','saga');assert.equal(await page.inputValue('#loan-deposit'),'3899');
 await page.selectOption('#advisor-variant','1.5 Premium');assert.equal(await page.inputValue('#loan-deposit'),'4999');
 await go('model/s70');await page.selectOption('#variant','1.5TD Flagship');
 await page.getByRole('button',{name:'Banding varian S70'}).click();await page.waitForURL('**/#compare');
 await page.selectOption('[data-cmp-variant="1"]','1.5TD Flagship');
 assert.match(await page.locator('.comparison-table').textContent(),/181 PS/);
 await page.check('#differences-only');assert.ok(!(await page.locator('.comparison-table').textContent()).includes('Beg udara'));
 await page.selectOption('[data-cmp-model="1"]','x90');await page.selectOption('[data-cmp-variant="1"]','1.5TD Prime X');
 assert.match(await page.locator('.comparison-table').textContent(),/122,800/);
 await go('test-drive');await page.fill('#booking-name','Aina & Ali');
 await page.selectOption('#advisor-model','s70');assert.equal(await page.inputValue('#booking-name'),'Aina & Ali');
 await page.selectOption('#advisor-variant','1.5 Prime');
 const date=new Date(Date.now()+2*86400000).toISOString().slice(0,10);
 await page.fill('#booking-date',date);await page.fill('#booking-time','15:30');
 await page.evaluate(()=>{window.open=(url)=>{window.__testWhatsapp=url;return null;};});
 await page.getByRole('button',{name:'Buka WhatsApp Khairun'}).click();
 const wa=new URL(await page.evaluate(()=>window.__testWhatsapp));assert.equal(wa.pathname,'/60172032996');
 const message=wa.searchParams.get('text');for(const text of ['Aina & Ali','1.5 Prime',date,'15:30'])assert.ok(message.includes(text));
 await page.screenshot({path:'test-output/test-drive-mobile.png',fullPage:true});
 await go('summary');await page.selectOption('#trade','yes');await page.fill('[data-old="model"]','Myvi');
 assert.match(await page.locator('#message').textContent(),/Myvi/);await page.uncheck('#tradeShare');assert.ok(!(await page.locator('#message').textContent()).includes('Myvi'));
 await go('promotions');assert.match(await page.locator('#app').textContent(),/sebelum rebat/);
 const routes=['home','catalog','model/saga','model/s70','model/x50','model/x70','model/x90','compare','loan','test-drive','promotions','summary'];
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:900});
  for(const route of routes){await go(route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Horizontal overflow at ${width} / ${route}`);}
 }
 await go('model/s70');await page.selectOption('#variant','1.5TD Flagship');
 await page.screenshot({path:'test-output/showroom-desktop.png',fullPage:true});
 await page.screenshot({path:'test-output/showroom-preview.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-output/showroom-mobile.png',fullPage:true});
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
 await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await context.setOffline(true);await page.reload();assert.match(await page.locator('h1').textContent(),/S70/);
 await page.locator('.app-nav a[href="#loan"]').click();assert.match(await page.locator('#loan-result').textContent(),/RM/);
 await context.setOffline(false);
 assert.deepEqual(errors,[]);
 console.log('PASS: real browser matching, seven-seat filter, variant/price sync, loan boundaries, compare, test-drive URL, trade-in privacy, 48 responsive routes and offline reload. No messages sent.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
