import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const ids=['saga','s70','x50','x70','x90'];
const models=Object.fromEntries(ids.map(id=>[id,JSON.parse(fs.readFileSync(path.join(root,'data',id+'.json'),'utf8'))]));
const promotions=JSON.parse(fs.readFileSync(path.join(root,'data/promotions.json'),'utf8'));
fs.writeFileSync(path.join(root,'showroom-data.js'),'// Generated by scripts/build-data.mjs. Edit data/*.json instead.\nglobalThis.SHOWROOM_DATA='+JSON.stringify({models,promotions})+';\n'+
  "PM.reviewed='4 Oktober 2026';\nfor(const m of PM.catalog){const d=SHOWROOM_DATA.models[m.id];m.variants=d.variants.map(v=>v.name);if(new Set(d.variants.map(v=>v.seats)).size>1)m.variantSeats=Object.fromEntries(d.variants.map(v=>[v.name,v.seats]));m.variantSource=d.brochure;m.reviewed=PM.reviewed;}\n");
console.log('Built showroom-data.js from six JSON files.');
